In [1]:
!pip install keras

You should consider upgrading via the 'C:\Users\Mscit8\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install tensorflow

  Using cached wheel-0.45.1-py3-none-any.whl (72 kB)


You should consider upgrading via the 'C:\Users\Mscit8\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import keras

In [4]:
import tensorflow as tf

In [14]:
 x=tf.constant([1,2,3,4,5,6],shape=[2,3])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
y=tf.constant([7,8,9,10,11,12],shape=[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [17]:
z=tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [18]:
A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32)
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6.228286 , 6.569197 ],
       [4.7863626, 3.6327891]], dtype=float32)>

In [21]:
eigen_values,eigen_vectors = tf.linalg.eigh(A)

In [22]:
print(eigen_values)

tf.Tensor([-0.02863775  9.889713  ], shape=(2,), dtype=float32)


In [23]:
print(eigen_vectors)

tf.Tensor(
[[-0.6075828  0.7942564]
 [ 0.7942564  0.6075828]], shape=(2, 2), dtype=float32)
